spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.147.6:3306/plant_lease_dev?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: dev
    password: dev23_mysql_5
    validationQuery: select 1
    testOnBorrow: true
  # REDIS (RedisProperties)
  redis:
    database: 5
    host: 106.15.190.65
    password: dev20_redis
    port: 6379
    pool.max-idle: 8
    pool.min-idle: 0
    pool.max-active: 8
    pool.max-wait: -1
    #sentinel.master:
    #sentinel.nodes:
  http:
    multipart:
      maxFileSize: 2Mb
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#######################
#### http server   ####
#######################
server:
  ip: localhost
  port: 10001


#######################
#### LOG           ####
#######################
logging:
  config: classpath:log4j2-dev.yml
  level:
    com.youzidata: DEBUG

upload:
  path: /liuxiangjun/nginx/www/upload
  goods:
    imgsPath: /imgs/goods
    contentPath: /imgs/goods

download:
  path: /liuxiangjun/nginx/www/download

